spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #swagger 설정
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: org.h2.Driver  # Database를 H2로 사용하겠다.
    url: jdbc:h2:mem:testdb  # H2 접속 정보
    username: sa  # H2 접속 시 입력할 username 정보 (원하는 것으로 입력)
    password:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          default:
            connect-timeout: 2000
            read-timeout: 5000
            logger-level: full

naver:
  openapi-url: https://openapi.naver.com
  url:
    search:
      local: https://openapi.naver.com/v1/search/local.json
      image: https://openapi.naver.com/v1/search/image
  client:
    id: uWNPYItMQRRryVqw2KpN
    secret: BdOft6BI6A

logging:
  level:
    com.snailvoyager.springbootnavermap.naver.NaverFeignClient: debug
